// const baseUrl = 'http://68.183.35.111/api/'
const baseUrl = "https://stutern-api.herokuapp.com/api/";
export const allUsers = `${baseUrl}users`;
export const allSets = `${baseUrl}sets`;
export const jobTitles = `${baseUrl}job-title`;
export const projects = `${baseUrl}user-projects`;
export const tracks = `${baseUrl}tracks`;
export const scholarships = `${baseUrl}scholarships`;
export const skills = `${baseUrl}skills`;
